# Generated by Django 4.2.6 on 2023-10-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ShortTermCourse_image')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField(max_length=100)),
                ('description', models.TextField()),
                ('subtitle', models.TextField()),
                ('status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=30)),
            ],
        ),
    ]
